version: '3.8'

services:
  master_server:
    build:
      context: ./master-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Replace with the actual port the master server uses
    volumes:
      - ./master-server:/app
    networks:
      - app-network

  game_server:
    build:
      context: ./game-server
      dockerfile: Dockerfile
    ports:
      - "9000:9000" # Replace with the actual port the game server uses
    volumes:
      - ./game-server:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
